# Generated by Django 4.2.10 on 2025-05-23 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("date", models.DateTimeField()),
                ("open_price", models.FloatField(blank=True, null=True)),
                ("high_price", models.FloatField(blank=True, null=True)),
                ("low_price", models.FloatField(blank=True, null=True)),
                ("close_price", models.FloatField(blank=True, null=True)),
                ("volume", models.BigIntegerField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Activo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("cantidad", models.IntegerField(default=1)),
                ("precioCompra", models.FloatField()),
                ("precioActual", models.FloatField(null=True)),
                ("precioVenta", models.FloatField(null=True)),
                ("fechaCompra", models.DateTimeField(auto_now_add=True)),
                ("fechaVenta", models.DateTimeField(null=True)),
                (
                    "recomendacion",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
