# Generated by Django 4.2.10 on 2024-04-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activo_fechacompra_activo_fechaventa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='precio',
            new_name='precioCompra',
        ),
        migrations.AddField(
            model_name='activo',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activo',
            name='precioVenta',
            field=models.FloatField(null=True),
        ),
    ]
