# Generated by Django 4.2.10 on 2024-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_precio_activo_preciocompra_activo_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='precioActual',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
    ]
