# Generated by Django 4.2.10 on 2024-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activo_precioactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='precioActual',
            field=models.FloatField(null=True),
        ),
    ]
