# Generated by Django 4.2.10 on 2024-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_activo_precioactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='recomendacion',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
