version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./data/static:/static
      - ./data/backend_state:/opt/state        # ← persiste el sentinela
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - internet_access
      - internal_network
    restart: unless-stopped
    depends_on:
      - timescaledb
    

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./data/frontend:/app/dist
    networks:
      - internet_access
      - internal_network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./data/static:/static
      - ./data/frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    networks:
      - internet_access
      - internal_network
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_DB: tesis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/timescaledb_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d   # ← one-shot scripts
    networks:
      - internet_access
      - internal_network
    restart: unless-stopped

networks:
  internal_network:
    driver: bridge
    internal: true
  internet_access:
    driver: bridge
    internal: false
