version: "3.8"

services:

  backend:
    build:
      context: ./backend
    volumes:
      - ./data/static:/static
      - ./data/backend_state:/opt/state
    env_file: ./backend/.env
    networks:
      - internal_network
    restart: unless-stopped
    depends_on:
      timescaledb:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./data/static:/static
    networks:
      - internet_access
      - internal_network
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_DB: tesis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/timescaledb_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - internal_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  internal_network:
    driver: bridge
  internet_access:
    driver: bridge
