version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - static:/app/static
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/dist
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_DB: tesis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d  # <-- Montamos los scripts
    restart: unless-stopped

volumes:
  static:
  frontend:
  timescaledb_data:
