services:
  backend:
    build:
      context: ./backend
    volumes:
      - static:/static
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb
    restart: unless-stopped  # Reiniciar autom치ticamente

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/dist
    restart: unless-stopped  # Reiniciar autom치ticamente

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped  # Reiniciar autom치ticamente

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_DB: tesis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped  # Reiniciar autom치ticamente

volumes:
  static:
  frontend:
  timescaledb_data:
