version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./data/static:/app/static
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb
    networks:
      - internet_access          # ⇦ acceso hacia afuera
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./data/frontend:/app/dist
    networks:
      - internet_access
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./data/static:/static
      - ./data/frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - internet_access
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_DB: tesis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/timescaledb_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - internet_access
    restart: unless-stopped



networks:
  internet_access:
    driver: bridge
    internal: false   # <-- garantiza salida a Internet
